### ISSUE TITLE
What is "data" in "chewie_preprocess_data.m"?

### ISSUE THREAD

**Issue by dhino2000** [zhd96/pi-vae#3]
Hello,

Thank you for sharing this great code! 
I am afraid this is a beginner question, but what does "data" in line 4 of "chewie_preprocess_data.m" refer to?

Best regards

**Comment by zhd96** [comment]
Hi,

Thanks for your interest! It's the monkey reaching data in our NeurIPS paper. But this data is not publicly available. If you want to explore this code, you can start with the simulated data examples or the rat data example.
