### ISSUE TITLE
Run on GPUs

### ISSUE THREAD

**Issue by gnlup** [zhd96/pi-vae#4]
Hi, I'm very interested in pi-VAE and want to use it on my own data. I noticed that there doesn't seem to be an explicit way to set the GPU device in `pi_vae.py`. Is there a way to use a GPU with pi-VAE? Or maybe I miss any important configuration in the code for GPU usage?

**Comment by zhd96** [comment]
Hi, thanks for your interest in pi-VAE. Unfortunately, this code doesn't support GPU device now. If your data is not too big, running it on CPU should be able to handle.
